package repo

const STATE_INIT = "INIT"
const STATE_DEPLOYING = "DEPLOYING"
const STATE_RUNNING = "RUNING"
const STATE_FAIL = "FAIL"
const STATE_FINISH = "FINISH"
const STATE_CANCEL = "CANCEL"

const INIT_STATE_DEPLOYING = "DEPLOYING"
const INIT_STATE_FINISH = "FINISH"
const INIT_STATE_FAIL = "FAIL"
const INIT_STATE_INIT = "INIT"